### ISSUE TITLE
UI/UX Progress Indicator dan Error Reporting

### ISSUE THREAD

**Issue by akbarr4m4dhani** [agusnurwanto/sipd-ri-penatausahaan-chrome-extension#4]
## Deskripsi
Tampilan progress dan pesan error saat ini kurang informatif bagi pengguna. Diperlukan perbaikan UI/UX untuk memberikan informasi yang lebih jelas.

### Masalah yang Ada
1. Progress indicator terlalu sederhana (`wrap-loading`)
2. Pesan error tidak detail
3. Tidak ada informasi estimasi waktu
4. Status proses tidak jelas

### Usulan Perbaikan

1. Progress UI yang Lebih Informatif:
```html
<div class="progress-container">
    <div class="progress-header">
        <h3>Sinkronisasi SP2D</h3>
        <span class="status">Sedang Berjalan</span>
    </div>
    <div class="progress-bar">
        <div class="progress" style="width: 45%"></div>
    </div>
    <div class="progress-details">
        <div class="item">
            <span>Total Data:</span>
            <strong>150</strong>
        </div>
        <div class="item">
            <span>Berhasil:</span>
            <strong>68</strong>
        </div>
        <div class="item">
            <span>Gagal:</span>
            <strong>2</strong>
        </div>
        <div class="item">
            <span>Estimasi:</span>
            <strong>~5 menit</strong>
        </div>
    </div>
</div>
```

2. Error Reporting yang Lebih Detail:
```javascript
class ErrorReporter {
    static show(error) {
        const container = document.createElement('div');
        container.className = 'error-container';
        
        // Template error
        container.innerHTML = `
            <div class="error-message">
                <h4>${error.title}</h4>
                <p>${error.message}</p>
                <div class="error-actions">
                    <button onclick="retryProcess('${error.id}')">Coba Lagi</button>
                    <button onclick="skipProcess('${error.id}')">Lewati</button>
                </div>
                <div class="error-detail">
                    <small>Error Code: ${error.code}</small>
                    <small>Time: ${new Date().toLocaleString()}</small>
                </div>
            </div>
        `;
        
        document.body.appendChild(container);
    }
}
```

3. Style untuk Progress dan Error:
```css
.progress-container {
    padding: 1rem;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.progress-bar {
    height: 8px;
    background: #eee;
    border-radius: 4px;
    overflow: hidden;
}

.progress {
    height: 100%;
    background: #4CAF50;
    transition: width 0.3s ease;
}

.error-container {
    position: fixed;
    bottom: 20px;
    right: 20px;
    max-width: 400px;
    z-index: 1000;
}
```

### Kriteria Selesai
- [ ] Progress indicator yang detail dan informatif
- [ ] Error reporting yang jelas dan actionable
- [ ] Estimasi waktu yang akurat
- [ ] Tampilan status yang real-time
- [ ] Dokumentasi penggunaan komponen
- [ ] Support untuk mobile view

### Technical Notes
- Gunakan CSS Grid/Flexbox untuk layout
- Implementasi animasi yang smooth
- Responsif untuk berbagai ukuran layar
- Aksesibilitas (WCAG compliance)
- Support untuk dark/light mode
